spring.application.name=SoltanSalman


#spring.data.mongodb.host=${MONGODB_HOST}
#spring.data.mongodb.port=${MONGODB_PORT}
#spring.data.mongodb.authentication-database=${MONGODB_AUTH_DB}
#spring.data.mongodb.username=${MONGODB_USERNAME}
#spring.data.mongodb.password=${MONGODB_PASSWORD}
spring.data.mongodb.database=${MONGODB_DATABASE}
spring.data.mongodb.uri=${MONGODB_URI}

-Dhttps.protocols=TLSv1.2

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

